name: Build

# We are a reusable Workflow only
on:
  workflow_call:
    secrets:
      SLACK_WEBHOOK_URL:
        required: false

jobs:
  build:
    name: Ant Build
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '__CI__')"

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache

    # It's important this runs BEFORE the ant build increments the build number
    - name: Read version
      id: current_version
      # For Maven builds (future)
      # run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
      # For Ant builds (still the default)
      run: echo "VERSION=`ant -silent -quiet version`" >> $GITHUB_ENV

    - name: Build with Ant
      run: ant -noinput -verbose -buildfile build.xml

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: hibernate_${{ env.VERSION }}.lex
        path: dist/*.lex