name: Build and Test

# We are a reusable Workflow only
on:
  workflow_call:
  push:
    branches-ignore:
        - main
        - master
  pull_request:
    branches-ignore:
        - main
        - master

jobs:
  build:
    name: Maven Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    strategy:
      fail-fast: false
      matrix:
        lucee_version: ["6.0.0.346-BETA"]
        java_version: [ "8", "11" ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '${{matrix.java_version}}'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: lucee-script-runner-maven-cache

    - name: Build with Maven
      run: mvn --batch-mode -f pom.xml -Dlucee.version=${{matrix.lucee_version}} -Djdk.version=${{matrix.java_version}} package

    - name: Checkout Lucee
      uses: actions/checkout@v3
      with:
        repository: lucee/lucee
        path: lucee

    - name: Cache Lucee files
      uses: actions/cache@v3
      with:
        path: _actions/lucee/script-runner/main/lucee-download-cache
        key: lucee-downloads-${{matrix.lucee_version}}
        restore-keys: |
          lucee-downloads

    - name: Run Lucee Test Suite (testLabels="orm")
      uses: lucee/script-runner@main
      with:
        webroot: ${{ github.workspace }}/lucee/test
        execute: /bootstrap-tests.cfm
        luceeVersion: ${{matrix.lucee_version}}
        extensionDir: ${{ github.workspace }}/target
      env:
        testLabels: orm
        testAdditional: ${{ github.workspace }}/tests

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.7.0
      if: always()
      with:
        files: ${{ github.workspace }}/lucee/test/reports/junit-test-results-${{matrix.lucee_version}}.xml
        check_name: "Test Results"