
# Rename [Unreleased] section in Changelog based on the current version in box.json
name: Changelog "Unreleased" Bumper

on: workflow_call

env:
  SNAPSHOT: ${{ github.ref_name != 'main' && github.ref_name != 'master' }}

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Read version
        id: current_version
        run: |
          export PACKAGE_VERSION=$( cat box.json | jq '.version' -r )
          echo "EXTENSION_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Check changelog for this version
        id: changelog_check
        run: |
          if grep -q "${{ env.EXTENSION_VERSION }}" CHANGELOG.md;then
            echo "HAS_VERSION=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_VERSION=false" >> $GITHUB_OUTPUT
          fi

      - name: Update changelog [unreleased] with latest version
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        if: "steps.changelog_check.outputs.HAS_VERSION == 'false' && !env.SNAPSHOT"
        with:
          changelogPath: ./CHANGELOG.md
          tag: ${{ env.EXTENSION_VERSION }}

      - name: Commit Changelog
        uses: EndBug/add-and-commit@v9.1.1
        if: "steps.changelog_check.outputs.HAS_VERSION == 'false' && !env.SNAPSHOT"
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: '📖 DOC: Finalized changelog for v${{ env.EXTENSION_VERSION }} - __CI__'
          add: CHANGELOG.md