name: Format Java Source

on: 
  workflow_dispatch:
    branches-ignore:
      - 'releases/**'
      - 'master'
      - 'development'
  push:
    branches-ignore:
      - 'releases/**'
      - 'master'
      - 'development'


jobs:
  format:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Format Java source code
        run: mvn --batch-mode -f pom.xml formatter:format

      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "docs"
          commit_message: "🤖 CI: Auto-format Java source __CI__"