# Publish Github Release
name: Github Release

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  update_gitbook:
    runs-on: ubuntu-latest
    # needs: release
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'ortus-docs/orm-extension'
          token: ${{ env.GH_TOKEN }}

      - name: Read the changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.0
        with:
          TAG_NAME: ${{ env.EXTENSION_VERSION }}
          CHANGELOG_FILE: CHANGELOG.md

      - name: Append Changelog to Release History doc
        run: |
          echo '# Release History' > release-history-NEW.md
          cat CHANGELOG.md >> release-history-NEW.md
          sed -i '' "1s/.*/`cat release-history-NEW.md`" intro/release-history.md

      - name: Commit changelog updates to docs repo
        uses: EndBug/add-and-commit@v9.1.1
        if: env.SNAPSHOT == 'false'
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: '📖 DOC: Add latest changelog to Release History doc - __CI__'
          add: intro/release-history.md