# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Extension Build

on: [push, pull_request, workflow_dispatch]
  branches-ignore:
      - main
      - master

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    uses: ./.github/workflows/test.yml

  maven_build:
    name: Maven Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    strategy:
      fail-fast: false
      matrix:
        lucee_version: ["5.3.10.97"]
        java_version: [ "8", "11", "17" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '${{matrix.java_version}}'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn --batch-mode -f pom.xml -Dlucee.version=${{matrix.lucee_version}} -Djdk.version=${{matrix.java_version}} compile
