name: Pull Requests

on:
  push:
    branches-ignore:
      - main
      - master
      - development
      - release/**
  pull_request:
    branches:
      - development

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  # Most incoming PRs from forks will not have the secrets or permissions needed to commit changes. Hence, we do formatter:validate and force the developer to fix the formatting themselves.
  checkJavaFormat:
    name: Validate Java Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Validate Java format
        run: mvn --batch-mode -f pom.xml formatter:validate

  # Most incoming PRs from forks will not have the secrets or permissions needed to commit changes. Hence, we do format:check and force the developer to fix the formatting themselves.
  checkCFMLFormat:
    name: Validate CFML Format
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: Ortus-Solutions/commandbox-action@v1.0.3
        with:
          cmd: run-script format:check
