
name: Publish a Release

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+.*

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  javadocs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Generate Javadocs
        run: mvn --batch-mode -f pom.xml javadoc:javadoc

      - name: Read version
        id: current_version
        # For Maven builds (future)
        # run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
        # For Ant builds (still the default)
        run: echo "VERSION=`ant -silent -quiet version`" >> $GITHUB_ENV

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_APIDOCS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "docs"
          DEST_DIR: "lucee/hibernate-extension/${{ env.VERSION }}/"

  gh_release:
    runs-on: ubuntu-latest
    needs: [build_and_test, javadocs]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Download built version number
        uses: actions/download-artifact@master
        with:
          name: extension-version

      - name: Read version file
        run: echo "VERSION=`cat version.txt`" >> $GITHUB_ENV

      - name: Read the changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.0
        with:
          TAG_NAME: ${{ env.VERSION }}

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: ortus_orm_${{ env.VERSION }}.lex
          path: .tmp/

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: .tmp/ortus_orm_${{ env.VERSION }}.lex
          replacesArtifacts: true
          tag: ${{ env.VERSION }}
          name: ${{ env.VERSION }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Upload Artifact to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/"
          DEST_DIR: "lucee/extensions/hibernate/${{ env.VERSION }}/"

      - name: Upload Logo to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "source/images/"
          DEST_DIR: "lucee/extensions/hibernate/"

  publish:
    runs-on: ubuntu-latest
    needs: [gh_release]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Download built version number
        uses: actions/download-artifact@master
        with:
          name: extension-version

      - name: Read version file
        run: echo "VERSION=`cat version.txt`" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_API_TOKEN }}

      - run: |
          box package set version=${{ env.VERSION }}
          box package set location="https://s3.amazonaws.com/downloads.ortussolutions.com/lucee/extensions/hibernate/${{ env.VERSION }}/ortus_orm_${{ env.VERSION }}.lex"
          box publish