
name: Publish a Release

on:
  push:
    branches:
      - main
      - master

jobs:
  javadocs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Generate Javadocs
        run: mvn --batch-mode -f pom.xml javadoc:javadoc

      - name: Read version
        id: current_version
        # For Maven builds (future)
        # run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
        # For Ant builds (still the default)
        run: echo "VERSION=`ant -silent -quiet version`" >> $GITHUB_ENV

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_APIDOCS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "docs"
          DEST_DIR: "lucee/hibernate-extension/${{ env.VERSION }}/"

  tag_and_release:
    runs-on: ubuntu-latest
    needs: [build, test, javadocs]
    steps:
      - uses: actions/checkout@v3

      - name: Get Version Tag
        id: current_version
        # For Maven builds (future)
        # run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
        # For Ant builds (still the default)
        run: echo "TAG=`ant -silent -quiet version`" >> $GITHUB_ENV

      - run: git tag -a ${{ env.TAG }}

      - name: Read the changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.0
        with:
          TAG_NAME: ${{ env.TAG }}

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: ${{ steps.tag_version.outputs.changelog }}

  publish:
    runs-on: ubuntu-latest
    needs: [tag_and_release]
    steps:
      - name: Get Project Version
        id: current_version
        # For Maven builds (future)
        # run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV
        # For Ant builds (still the default)
        run: echo "VERSION=`ant -silent -quiet version`" >> $GITHUB_ENV

      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: hibernate_${{ env.VERSION }}.lex
          path: dist/*.lex

      - name: Upload Artifact to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "dist/*.lex"
          DEST_DIR: "lucee/extensions/hibernate/${{ env.VERSION }}/"