
name: Publish a Release

on:
  # If you push to master|main this will trigger a stable release
  push:
    branches:
      - master
      - main
  workflow_dispatch:
  # Reusable workflow : Usually called by a `snapshot` workflow
  workflow_call:
    inputs:
      snapshot:
          description: 'Is this a snapshot build?'
          required: false
          default: false
          type: boolean

env:
  SNAPSHOT: ${{ inputs.snapshot || false }}

jobs:
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  javadocs:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Generate Javadocs
        run: mvn --batch-mode -f pom.xml javadoc:javadoc

      - name: Read version
        run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV

      - name: Upload API Docs to S3
        uses: jakejarvis/s3-sync-action@master
        if: env.SNAPSHOT == 'false'
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_APIDOCS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "docs"
          DEST_DIR: "lucee/hibernate-extension/${{ env.VERSION }}/"

  gh_release:
    if: "!contains(github.event.head_commit.message, '__CI__')"
    runs-on: ubuntu-latest
    needs: [build_and_test, javadocs]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Read version
        run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV

      - name: Build with Maven
        run: mvn --batch-mode -f pom.xml package

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ortus_orm_${{ env.VERSION }}.lex
          path: target/*.lex

      - run: |
            mkdir .tmp/
            mv target/*.lex .tmp/

      - name: Check for file
        id: changelog_check
        run: |
          if grep -q "${{ env.VERSION }}" CHANGELOG.md ]];then
            echo "HAS_VERSION=true" >> $GITHUB_OUTPUT
          else
            echo "HAS_VERSION=false" >> $GITHUB_OUTPUT
          fi

      - name: Update changelog [unreleased] with latest version
        uses: thomaseizinger/keep-a-changelog-new-release@1.3.0
        if: env.SNAPSHOT == 'false' && steps.changelog_check.outputs.HAS_VERSION == 'false'
        with:
          changelogPath: ./CHANGELOG.md
          tag: v${{ env.VERSION }}

      - name: Commit Changelog To Master
        uses: EndBug/add-and-commit@v9.1.1
        if: env.SNAPSHOT == 'false'
        with:
          author_name: Github Actions
          author_email: info@ortussolutions.com
          message: '📖 DOC: Finalized changelog for v${{ env.VERSION }} - __CI__'
          add: CHANGELOG.md

      - name: Tag Version
        uses: rickstaa/action-create-tag@v1.6.1
        if: env.SNAPSHOT == 'false'
        with:
          tag: "v${{ env.VERSION }}"
          force_push_tag: true
          tag_exists_error: false
          message: "Release v${{ env.VERSION }}"

      - name: Read the changelog
        id: changelog
        uses: 3liz/changelog-release@0.2.0
        with:
          TAG_NAME: ${{ env.VERSION }}
          CHANGELOG_FILE: CHANGELOG.md

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        if: env.SNAPSHOT == 'false'
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: .tmp/ortus_orm_${{ env.VERSION }}.lex
          replacesArtifacts: true
          tag: ${{ env.VERSION }}
          name: v${{ env.VERSION }}
          body: ${{ steps.changelog.outputs.markdown }}

      - name: Upload Artifact to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: ".tmp/"
          DEST_DIR: "lucee/extensions/hibernate/${{ env.VERSION }}/"

      - name: Upload Logo to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_SECRET }}
          SOURCE_DIR: "source/images/"
          DEST_DIR: "lucee/extensions/hibernate/"

  publish:
    runs-on: ubuntu-latest
    needs: [gh_release]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}

      - name: Read version
        run: echo "VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout`" >> $GITHUB_ENV

      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Setup CommandBox
        uses: Ortus-Solutions/setup-commandbox@main
        with:
          forgeboxAPIKey: ${{ secrets.FORGEBOX_API_TOKEN }}

      - run: |
          box package set version=${{ env.VERSION }}
          box package set location="https://s3.amazonaws.com/downloads.ortussolutions.com/lucee/extensions/hibernate/${{ env.VERSION }}/ortus_orm_${{ env.VERSION }}.lex"
          box publish