name: Snyk Vulnerability Scan

on:
  workflow_call:

jobs:
  scan:
    name: Run Vulnerability Scan with Snyk
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '__CI__')"
    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-11@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif