name: Build Snapshot

on:
  push:
    branches:
      - 'development'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    needs: [ build_and_test ]
    secrets: inherit
    with:
      snapshot: true