name: Build Snapshot

on:
  push:
    branches:
      - 'development'

jobs:
  ##########################################################################################
  # Module Tests
  ##########################################################################################
  build_and_test:
    uses: ./.github/workflows/build_and_test.yml

  ##########################################################################################
  # Release it
  ##########################################################################################
  release:
    uses: ./.github/workflows/release.yml
    needs: [ build_and_test ]
    secrets: inherit
    with:
      snapshot: true